
# GET 

GET http://localhost:9021/key?kv=9021 HTTP/1.1


### POST

POST http://localhost:9021/dhke HTTP/1.1
content-type: application/json

# {
#     "publicKey": "Diffie Hellmans\n Mayo"
# }

# {
#     "publicKey": "-----BEGIN PUBLIC KEY-----\nMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAER2bB7I8w6EZM7I8jI0HH4ceWIK6ZASqkUZUDsbLrhjG0B3+xEUgRSekUmZOgqKrw/f0cpU2cZ9/FT97RNv1U+g==\n-----END PUBLIC KEY-----"

# }
{
    "publicKey": "-----BEGIN PUBLIC KEY-----\nMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE1wzikWmo5qpAxIccvX0KccteR24VH6DHeGSSLt3UAmMobAun0eGl+BKvUNLbR8fqhLK/PnutlPAcvoeAJLIoTw==\n-----END PUBLIC KEY-----\n"

}


### POST CHECK AES

POST http://localhost:9021/storeSecret HTTP/1.1
content-type: application/json

{
  "ciphertext": "JyQYNnCOTpc4azlebPNnRHOOrwF05L32ZAq2lm4G",
  "iv": "z3HJC5+vpsrq24kI"
}

